language: ruby
rvm:
  - 2.4.2
before_script:
  - bundle exec rails db:create --all
  - bundle exec rails db:migrate
script:
  - bundle exec rake ci:tests
services:
  - postgresql
notifications:
  email: false
