version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 4001 -b '0.0.0.0'
    volumes:
      - .:/standup_app
    ports:
      - '4001:4001'
    depends_on:
      - db
